# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapshot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='snapshot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0esnapshot.proto\"\xbf\x01\n\x11SnapshotFormatted\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\x04\x12\x1c\n\x04pose\x18\x02 \x01(\x0b\x32\x0e.PoseFormatted\x12)\n\x0b\x63olor_image\x18\x03 \x01(\x0b\x32\x14.ColorImageFormatted\x12)\n\x0b\x64\x65pth_image\x18\x04 \x01(\x0b\x32\x14.DepthImageFormatted\x12$\n\x08\x66\x65\x65lings\x18\x05 \x01(\x0b\x32\x12.FeelingsFormatted\"\xf7\x01\n\rPoseFormatted\x12\x38\n\x0btranslation\x18\x01 \x01(\x0b\x32#.PoseFormatted.TranslationFormatted\x12\x32\n\x08rotation\x18\x02 \x01(\x0b\x32 .PoseFormatted.RotationFormatted\x1a\x37\n\x14TranslationFormatted\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a?\n\x11RotationFormatted\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"B\n\x13\x43olorImageFormatted\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"B\n\x13\x44\x65pthImageFormatted\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"Z\n\x11\x46\x65\x65lingsFormatted\x12\x0e\n\x06hunger\x18\x01 \x01(\x02\x12\x0e\n\x06thirst\x18\x02 \x01(\x02\x12\x12\n\nexhaustion\x18\x03 \x01(\x02\x12\x11\n\thappiness\x18\x04 \x01(\x02\x62\x06proto3'
)




_SNAPSHOTFORMATTED = _descriptor.Descriptor(
  name='SnapshotFormatted',
  full_name='SnapshotFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='SnapshotFormatted.datetime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='SnapshotFormatted.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_image', full_name='SnapshotFormatted.color_image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth_image', full_name='SnapshotFormatted.depth_image', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feelings', full_name='SnapshotFormatted.feelings', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=210,
)


_POSEFORMATTED_TRANSLATIONFORMATTED = _descriptor.Descriptor(
  name='TranslationFormatted',
  full_name='PoseFormatted.TranslationFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseFormatted.TranslationFormatted.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseFormatted.TranslationFormatted.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseFormatted.TranslationFormatted.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=395,
)

_POSEFORMATTED_ROTATIONFORMATTED = _descriptor.Descriptor(
  name='RotationFormatted',
  full_name='PoseFormatted.RotationFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PoseFormatted.RotationFormatted.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PoseFormatted.RotationFormatted.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PoseFormatted.RotationFormatted.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='PoseFormatted.RotationFormatted.w', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=460,
)

_POSEFORMATTED = _descriptor.Descriptor(
  name='PoseFormatted',
  full_name='PoseFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='PoseFormatted.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='PoseFormatted.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSEFORMATTED_TRANSLATIONFORMATTED, _POSEFORMATTED_ROTATIONFORMATTED, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=460,
)


_COLORIMAGEFORMATTED = _descriptor.Descriptor(
  name='ColorImageFormatted',
  full_name='ColorImageFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ColorImageFormatted.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ColorImageFormatted.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ColorImageFormatted.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=528,
)


_DEPTHIMAGEFORMATTED = _descriptor.Descriptor(
  name='DepthImageFormatted',
  full_name='DepthImageFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='DepthImageFormatted.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='DepthImageFormatted.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DepthImageFormatted.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=596,
)


_FEELINGSFORMATTED = _descriptor.Descriptor(
  name='FeelingsFormatted',
  full_name='FeelingsFormatted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hunger', full_name='FeelingsFormatted.hunger', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thirst', full_name='FeelingsFormatted.thirst', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exhaustion', full_name='FeelingsFormatted.exhaustion', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='happiness', full_name='FeelingsFormatted.happiness', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=688,
)

_SNAPSHOTFORMATTED.fields_by_name['pose'].message_type = _POSEFORMATTED
_SNAPSHOTFORMATTED.fields_by_name['color_image'].message_type = _COLORIMAGEFORMATTED
_SNAPSHOTFORMATTED.fields_by_name['depth_image'].message_type = _DEPTHIMAGEFORMATTED
_SNAPSHOTFORMATTED.fields_by_name['feelings'].message_type = _FEELINGSFORMATTED
_POSEFORMATTED_TRANSLATIONFORMATTED.containing_type = _POSEFORMATTED
_POSEFORMATTED_ROTATIONFORMATTED.containing_type = _POSEFORMATTED
_POSEFORMATTED.fields_by_name['translation'].message_type = _POSEFORMATTED_TRANSLATIONFORMATTED
_POSEFORMATTED.fields_by_name['rotation'].message_type = _POSEFORMATTED_ROTATIONFORMATTED
DESCRIPTOR.message_types_by_name['SnapshotFormatted'] = _SNAPSHOTFORMATTED
DESCRIPTOR.message_types_by_name['PoseFormatted'] = _POSEFORMATTED
DESCRIPTOR.message_types_by_name['ColorImageFormatted'] = _COLORIMAGEFORMATTED
DESCRIPTOR.message_types_by_name['DepthImageFormatted'] = _DEPTHIMAGEFORMATTED
DESCRIPTOR.message_types_by_name['FeelingsFormatted'] = _FEELINGSFORMATTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SnapshotFormatted = _reflection.GeneratedProtocolMessageType('SnapshotFormatted', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTFORMATTED,
  '__module__' : 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:SnapshotFormatted)
  })
_sym_db.RegisterMessage(SnapshotFormatted)

PoseFormatted = _reflection.GeneratedProtocolMessageType('PoseFormatted', (_message.Message,), {

  'TranslationFormatted' : _reflection.GeneratedProtocolMessageType('TranslationFormatted', (_message.Message,), {
    'DESCRIPTOR' : _POSEFORMATTED_TRANSLATIONFORMATTED,
    '__module__' : 'snapshot_pb2'
    # @@protoc_insertion_point(class_scope:PoseFormatted.TranslationFormatted)
    })
  ,

  'RotationFormatted' : _reflection.GeneratedProtocolMessageType('RotationFormatted', (_message.Message,), {
    'DESCRIPTOR' : _POSEFORMATTED_ROTATIONFORMATTED,
    '__module__' : 'snapshot_pb2'
    # @@protoc_insertion_point(class_scope:PoseFormatted.RotationFormatted)
    })
  ,
  'DESCRIPTOR' : _POSEFORMATTED,
  '__module__' : 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:PoseFormatted)
  })
_sym_db.RegisterMessage(PoseFormatted)
_sym_db.RegisterMessage(PoseFormatted.TranslationFormatted)
_sym_db.RegisterMessage(PoseFormatted.RotationFormatted)

ColorImageFormatted = _reflection.GeneratedProtocolMessageType('ColorImageFormatted', (_message.Message,), {
  'DESCRIPTOR' : _COLORIMAGEFORMATTED,
  '__module__' : 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:ColorImageFormatted)
  })
_sym_db.RegisterMessage(ColorImageFormatted)

DepthImageFormatted = _reflection.GeneratedProtocolMessageType('DepthImageFormatted', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHIMAGEFORMATTED,
  '__module__' : 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:DepthImageFormatted)
  })
_sym_db.RegisterMessage(DepthImageFormatted)

FeelingsFormatted = _reflection.GeneratedProtocolMessageType('FeelingsFormatted', (_message.Message,), {
  'DESCRIPTOR' : _FEELINGSFORMATTED,
  '__module__' : 'snapshot_pb2'
  # @@protoc_insertion_point(class_scope:FeelingsFormatted)
  })
_sym_db.RegisterMessage(FeelingsFormatted)


# @@protoc_insertion_point(module_scope)
